library(rmarkdown)
decks <- list.files("./rmd", "\\.rmd$", full.names=T)
render(decks[1], knit_root_dir="..", output_dir="./slides")
render(decks[2], knit_root_dir="..", output_dir="./slides")
render(decks[3], knit_root_dir="..", output_dir="./slides")
render(decks[5], knit_root_dir="..", output_dir="./slides")
